spring:
  application:
    name: tp-bd2
  # Configuración para el autoconfigurador de Spring Data
  mongodb:
    host: localhost
    port: 27017
    database: tp_bd2
    username: admin
    password: admin123
    authentication-database: admin
    uri: mongodb://admin:admin123@localhost:27017/tp_bd2?authSource=admin

app:
  json-output: ./output/ventas.json

server:
  port: 8080